[package]
name = "paradox-patch"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "5.9.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
thiserror = "1.0.40"
tracing = "0.1.37"
